sonar.projectKey=ahmed-magdi2712_DevSecOps-Usecase
sonar.projectName=DevSecOps-Usecase
sonar.organization=devsecops-poc
sonar.projectVersion=1.0.0

# Source & tests
sonar.sources=src/app
sonar.tests=src/app/tests
sonar.sourceEncoding=UTF-8
sonar.language=py

# Exclusions
sonar.exclusions=**/tests/**,**/__pycache__/**,**/migrations/**,**/*.pyc
sonar.coverage.exclusions=**/tests/**,**/__pycache__/**,**/test_*.py,**/conftest.py
sonar.cpd.exclusions=**/tests/**

# Python-specific
sonar.python.version=3.13
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.python.xunit.reportPath=reports/junit-results.xml

# Quality gate
sonar.qualitygate.wait=true
