---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: secureapp-secrets
  namespace: secureapp-dev
  labels:
    app.kubernetes.io/name: secureapp
    app.kubernetes.io/component: backend
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 15s
  target:
    name: secureapp-secrets
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        DATABASE_URL: "{{ .DATABASE_URL | toString }}"
        REDIS_URL: "{{ .REDIS_URL | toString }}"
        SECRET_KEY: "{{ .SECRET_KEY | toString }}"
        PORT: "{{ .PORT | toString }}"
        RATE_LIMIT_REQUESTS: "{{ .RATE_LIMIT_REQUESTS | toString }}"
        CACHE_TTL: "{{ .CACHE_TTL | toString }}"
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: secret/data/secureapp
        property: DATABASE_URL
    - secretKey: REDIS_URL
      remoteRef:
        key: secret/data/secureapp
        property: REDIS_URL
    - secretKey: SECRET_KEY
      remoteRef:
        key: secret/data/secureapp
        property: SECRET_KEY
    - secretKey: PORT
      remoteRef:
        key: secret/data/secureapp
        property: PORT
    - secretKey: RATE_LIMIT_REQUESTS
      remoteRef:
        key: secret/data/secureapp
        property: RATE_LIMIT_REQUESTS
    - secretKey: CACHE_TTL
      remoteRef:
        key: secret/data/secureapp
        property: CACHE_TTL
