---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  labels:
    external-secrets: "true"
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"          # KV mount name
      version: "v2"           # KV version
      auth:
        kubernetes:
          mountPath: "kubernetes"          # auth/kubernetes
          role: "eso-role"                 # vault role from Step 3
          serviceAccountRef:
            name: "external-secrets"       # SA in ESO namespace
            namespace: "external-secrets"
