---
# yamllint disable rule:line-length
# Kubernetes Secret for pulling the private Docker Hub image karimkhaledopsera/pipeline-demo
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  labels:
    app.kubernetes.io/name: secureapp
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsiYXV0aCI6ImEyRnlhVzFyYUdGc1pXUnZjSE5sY21FNlpHTnJjbDl3WVhSZlUwOTJTMUIyTjFWS1QxQXlhMEZsUVdGcVluaFZWbWxvV2pKViJ9fX0=
# yamllint enable rule:line-length
