---
# yamllint disable rule:line-length
# Kubernetes Secret for pulling the private Docker Hub image karimkhaled842/pipeline-demo
apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  labels:
    app.kubernetes.io/name: secureapp
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsiYXV0aCI6ImEyRnlhVzFyYUdGc1pXUTROREk2WkdOcmNsOXdZWFJmVTA5MlMxQjJOMVZLVDFBeWEwRmxRV0ZxWW5oVlZtbG9XakpWIn19fQ==
# yamllint enable rule:line-length
