---
apiVersion: v1
kind: Service
metadata:
  name: secureapp
  labels:
    app.kubernetes.io/name: secureapp
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: secureapp
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secureapp
  labels:
    app.kubernetes.io/name: secureapp
  annotations: {}
automountServiceAccountToken: false
