---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secureapp-dev

resources:
  - ../../base

namePrefix: dev-

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: app
      spec:
        replicas: 1
        template:
          spec:
            containers:
              - name: api
                resources:
                  requests:
                    cpu: "50m"
                    memory: "128Mi"
                  limits:
                    cpu: "200m"
                    memory: "256Mi"

configMapGenerator:
  - behavior: merge
    literals:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
      - WORKERS=1
    name: secureapp-config

images:
  - digest: sha256:63589c63942568084a8a4718e6e1953a7979df45d3abc2094ecb480114e82849
    name: ghcr.io/ahmed-magdi2712/devsecops-usecase
    newName: ghcr.io/ahmed-magdi2712/devsecops-usecase
