apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: secureapp-dev

resources:
- ../../base

namePrefix: dev-

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: app
    spec:
      replicas: 1
      template:
        spec:
          containers:
            - name: api
              resources:
                requests:
                  cpu: "50m"
                  memory: "128Mi"
                limits:
                  cpu: "200m"
                  memory: "256Mi"

configMapGenerator:
- behavior: merge
  literals:
  - ENVIRONMENT=development
  - LOG_LEVEL=debug
  - WORKERS=1
  name: secureapp-config

images:
- digest: sha256:e082243e488abb01c68aae6727a75cdab05f73d1422f16e933f7cfb5cfc41699
  name: karimkhaledopsera/pipeline-demo
  newName: docker.io/karimkhaledopsera/pipeline-demo
